# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("accessibility.typeaheadfind", true);
user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1209996196);
user_pref("app.update.lastUpdateTime.background-update-timer", 1209996196);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1209996196);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1209996197);
user_pref("browser.history_expire_days.mirror", 9);
user_pref("browser.preferences.advanced.selectedTabIndex", 3);
user_pref("browser.search.update", false);
user_pref("browser.startup.homepage", "");
user_pref("browser.startup.homepage_override.mstone", "rv:1.8.1.14");
user_pref("browser.startup.page", 0);
user_pref("browser.tabs.autoHide", false);
user_pref("browser.tabs.warnOnClose", false);
user_pref("extensions.lastAppVersion", "2.0.0.14");
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.notifyUser", false);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.lifetimePolicy", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("urlclassifier.tableversion.goog-black-enchash", "1.50093");
user_pref("urlclassifier.tableversion.goog-black-url", "1.20653");
user_pref("urlclassifier.tableversion.goog-white-domain", "1.31");
user_pref("urlclassifier.tableversion.goog-white-url", "1.371");
